version: "3.9"

services:
  server:
    build: .
    command: python server/server.py
    ports:
      - "8080:8080"
    environment:
      - SERVER_IP=0.0.0.0
    depends_on:
      - ganache

  client0:
    build: .
    command: python client/client.py
    environment:
      - CLIENT_ID=0
      - TOTAL_CLIENTS=5

  client1:
    build: .
    command: python client/client.py
    environment:
      - CLIENT_ID=1
      - TOTAL_CLIENTS=5

  client2:
    build: .
    command: python client/client.py
    environment:
      - CLIENT_ID=2
      - TOTAL_CLIENTS=5

  client3:
    build: .
    command: python client/client.py
    environment:
      - CLIENT_ID=3
      - TOTAL_CLIENTS=5

  client4:
    build: .
    command: python client/client.py
    environment:
      - CLIENT_ID=4
      - TOTAL_CLIENTS=5

  ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
