version: "3"

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    networks:
      - fl_network

  server:
    build: .
    entrypoint: ["sh", "/app/server/entrypoint.sh"]
    ports:
      - "8080:8080"
    environment:
      - NUM_CLIENTS=3
    depends_on:
      - ganache
    networks:
      - fl_network

  client1:
    build: .
    command: python client/client.py
    environment:
      - SERVER_IP=server
      - SERVER_PORT=8080
      - CLIENT_ID=0
      - NUM_CLIENTS=3
    depends_on:
      - server
    networks:
      - fl_network

  client2:
    build: .
    command: python client/client.py
    environment:
      - SERVER_IP=server
      - SERVER_PORT=8080
      - CLIENT_ID=1
      - NUM_CLIENTS=3
    depends_on:
      - server
    networks:
      - fl_network

  client3:
    build: .
    command: python client/client.py
    environment:
      - SERVER_IP=server
      - SERVER_PORT=8080
      - CLIENT_ID=2
      - NUM_CLIENTS=3
    depends_on:
      - server
    networks:
      - fl_network

networks:
  fl_network:
    driver: bridge
